### ISSUE TITLE
Usage message

### ISSUE THREAD

**Issue by gbraad** [gbraad-actions/jupyter-action#2]

**Comment by gbraad** [comment]
```yaml
    - name: Hang around
      shell: bash
      run: |
        sleep 5
        echo "Open in a browser: http://${HOSTNAME}:8888"
```
